### ISSUE TITLE
PDF files not found

### ISSUE THREAD

**Issue by loesvs** [cycomanic/Menextract2pdf#2]
Hi Jochen

I would love to use your tool but I have an issue when running menextract2pdf.py: it appears to correctly read my Mendeley database, but it can't seem to find the accompanying pdf files. Output is a long list, e.g.:

Could not find pdffile D:\PapersMen\2010_Hatfull.pdf
Could not find pdffile D:\PapersMen\2012_Zhong et al.pdf
Could not find pdffile D:\PapersMen\1953_Bloch, Noll.pdf
Could not find pdffile D:\PapersMen\2011_Lawson, Norton, Clements.pdf
Could not find pdffile D:\PapersMen\2013_Goodman, Church, Kosuri.pdf

I saw in the code it's due to an I/O error when opening the file. However, I'm not familiar with pdf editing and I can't find out what's wrong. Note that the error is not limited to file names containing special characters (the upper one should be fine). When I copy a path from the error message and paste it in the command line, the pdf opens just fine.

Running Win7 64bit, Python 2.7, updated sqlite3 to get the script to work.

Would you know what happened?

Cheers
Loes

(Also: line 109 has an extra dot after ['notes'])

**Comment by cycomanic** [comment]
Hi Loes,
thanks for the report. I'm running Linux, but will try to find a windows machine to see what's happening. By special character do you mean the commas?

**Comment by loesvs** [comment]
Hi

Yes, I meant the commas - no problems with that. The files are present at the given paths - when I just copy paste the paths to the command line, they open as they should.

In the meantime, I used Xunius's Menotexport tool (which incorporates your pdf annotation) to complete my Mendeley-to-Zotero transition, so I didn't troubleshoot it further.

Thank you for looking into it anyways!

Loes
